<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Biome.fs" />
    <Compile Include="InMemory.fs" />
    <Compile Include="File.fs" />
    <Compile Include="Json.fs" />
    <None Include="investigate_json.fsx" />
    <None Include="Sandbox.fsx" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharp.Control.TaskSeq" Version="1.0.0" />
  </ItemGroup>

</Project>
